### ISSUE TITLE
Does this board support SDIO mode

### ISSUE THREAD

**Issue by langyxxl** [carlk3/no-OS-FatFS-SD-SDIO-SPI-RPi-Pico#12]
https://www.waveshare.com/wiki/RP2040-GEEK

**Comment by carlk3** [comment]
The requirements are:
> Pins CLK_gpio, D1_gpio, D2_gpio, and D3_gpio are at offsets from pin D0_gpio.
> The offsets are determined by sd_driver\SDIO\rp2040_sdio.pio.
>     CLK_gpio = (D0_gpio + SDIO_CLK_PIN_D0_OFFSET) % 32;
>     As of this writing, SDIO_CLK_PIN_D0_OFFSET is 30,
>         which is -2 in mod32 arithmetic, so:
>     CLK_gpio = D0_gpio -2.
>     D1_gpio = D0_gpio + 1;
>     D2_gpio = D0_gpio + 2;
>     D3_gpio = D0_gpio + 3;

Looking at the schematic, I'd say it should work fine:

![image](https://github.com/carlk3/no-OS-FatFS-SD-SDIO-SPI-RPi-Pico/assets/50121841/b91b904b-b70b-4648-bab8-1d3ea950d97f)
