### ISSUE TITLE
SDIO Walkthrough

### ISSUE THREAD

**Issue by mjamshid98** [carlk3/no-OS-FatFS-SD-SDIO-SPI-RPi-Pico#38]
Dear Carl,

I really appreciate your library. I was acquainted with it through the DigiKey tutorial, and used SPI connection to the  'Adafruit Micro SD SPI or SDIO Card Breakout Board' writing directly to the txt file after reading input from an ADC. I am achieving around 32 kHz. I'm trying to get higher numbers, and I have moved on to your new repository which supports SDIO. 
The issue I'm facing is that, after I connect the pico to the pins assigned in the 'simple_sdio' example, i.e. D0 -> Pico GPIO 18, CMD -> Pico GPIO 17, CLK-> GPIO 16 and the D1-D3 offset the respective 1-3 amounts, and I don't make any changed to the config files (I don't know if I should), and flash the pico and load the uf2 file of the 'simple_sdio' example, the pico doesn't do anything. It doesn't even reconnect to a COM port for serial output, meaning it probably doesn't even reach the main function. 

The only thing I can think of is that I may have needed to modify the hardware config files, but I really don't know how to do that, as I am relatively new to C. 
Any help would really be appreciated.

**Comment by carlk3** [comment]
If you compare the [CMakeLists.txt](https://github.com/carlk3/no-OS-FatFS-SD-SDIO-SPI-RPi-Pico/blob/main/examples/simple_sdio/CMakeLists.txt) with your previous (working) CMakeLists.txt are there any differences that could explain the serial output problem?  E.g., `pico_enable_stdio`?

Maybe it's an electrical problem. You could try disconnecting the SD card completely and see if you can at least get serial output from the 'simple_sdio' example. If you don't at least get a "Hello, world!" out of that, I would suggest turning to Chapter 4., _Saying "Hello World" in C_, in [Getting started with Raspberry Pi Pico](https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf).
