### ISSUE TITLE
Detecting card without CD pin

### ISSUE THREAD

**Issue by willeccles** [carlk3/no-OS-FatFS-SD-SDIO-SPI-RPi-Pico#39]
Our hardware has a hinged SD card slot, and those don't typically have a CD pin for obvious reasons. At the moment, I am just calling `f_mount` and relying on the result being `FR_NOT_READY` if there is no SD card present. Is this the recommended way? I had a gander through the source and couldn't find any other appealing way to do this, but I'd like to confirm.

**Comment by carlk3** [comment]
Have a look at [(dev_sdio) Added sd_test_com() which can be used to quickly test the presence of SD card when card detect is not used](https://github.com/carlk3/no-OS-FatFS-SD-SPI-RPi-Pico/pull/60).
